version: "3"
services:
  postgres:
    image: "postgres:13-alpine"
    networks:
      - subji-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: subji
  subji:
    build: .
    networks:
      - subji-network
    ports:
      - "19093:8080"
    depends_on:
      - postgres
networks:
  subji-network:
    driver: bridge
