version: "3"

services: 
  postgres:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: subji
    ports:
      - "5432:5432"
      